/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:32bb1b77-5bf0-4eb1-96a9-6237d02c5af0",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_36yUd6nGD",
    "aws_user_pools_web_client_id": "1o6g1a3uhbrgjbj52v5gkngolr",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://xyjf5a5kmnbyfe63k2f4khqsxe.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS"
};


export default awsmobile;
